DROP TABLE `destination`;

CREATE TABLE `destination` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `city` varchar(255),
  `country` varchar(100) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `destination` (`id`,`city`,`country`) VALUES (1,'Northallerton','Antigua and Barbuda'),(2,'Brussel','Austria'),(3,'Duncan','Uzbekistan'),(4,'Mobile','Trinidad and Tobago'),(5,'Eberswalde-Finow','Bulgaria'),(6,'Caucaia','Guatemala'),(7,'Rhemes-Saint-Georges','Gabon'),(8,'Cabras','Namibia'),(9,'Mâcon','South Georgia and The South Sandwich Islands'),(10,'West Jordan','Cameroon');
INSERT INTO `destination` (`id`,`city`,`country`) VALUES (11,'Tuscaloosa','Bermuda'),(12,'Hapur','Bonaire, Sint Eustatius and Saba'),(13,'Zittau','Serbia'),(14,'Castel Volturno','Pitcairn Islands'),(15,'Granada','Thailand'),(16,'Berceto','Swaziland'),(17,'Notre-Dame-de-la-Salette','Finland'),(18,'Lo Prado','Falkland Islands'),(19,'New Orleans','Dominica'),(20,'Perwez','Australia');
INSERT INTO `destination` (`id`,`city`,`country`) VALUES (21,'Westkapelle','Peru'),(22,'Germersheim','Honduras'),(23,'Stuttgart','Ecuador'),(24,'Goslar','Greenland'),(25,'Ayas','Kuwait'),(26,'Vollezele','South Georgia and The South Sandwich Islands'),(27,'Ludvika','Curaçao'),(28,'Reims','United States'),(29,'Sundrie','Cyprus'),(30,'Bergisch Gladbach','Bolivia');
INSERT INTO `destination` (`id`,`city`,`country`) VALUES (31,'Connah''s Quay','Cayman Islands'),(32,'San Diego','Lesotho'),(33,'Huntsville','Guyana'),(34,'Oristano','Denmark'),(35,'Fort Simpson','Greece'),(36,'Pogliano Milanese','Bouvet Island'),(37,'Vadodara','Jordan'),(38,'Saint-Étienne-du-Rouvray','French Guiana'),(39,'Kurnool','Uganda'),(40,'Vlezenbeek','Virgin Islands, British');
INSERT INTO `destination` (`id`,`city`,`country`) VALUES (41,'Hannover','United Kingdom (Great Britain)'),(42,'Huppaye','Denmark'),(43,'Lacombe','Guinea-Bissau'),(44,'Villanova d''Albenga','Hungary'),(45,'Lerum','Montserrat'),(46,'Town of Yarmouth','Luxembourg'),(47,'Naihati','Grenada'),(48,'Parkland County','Timor-Leste'),(49,'La Serena','Cuba'),(50,'Baie-Comeau','Reunion');
INSERT INTO `destination` (`id`,`city`,`country`) VALUES (51,'Padre Hurtado','Guyana'),(52,'My','Suriname'),(53,'Åkersberga','Venezuela'),(54,'Certaldo','Chad'),(55,'Ruisbroek','Angola'),(56,'Castelluccio Superiore','Pakistan'),(57,'San Bernardo','Burkina Faso'),(58,'Leverkusen','Georgia'),(59,'Teltow','Iceland'),(60,'Kortessem','Puerto Rico');
INSERT INTO `destination` (`id`,`city`,`country`) VALUES (61,'Curacautín','Bhutan'),(62,'North Las Vegas','Turks and Caicos Islands'),(63,'Souvret','Holy See (Vatican City State)'),(64,'Sandy','Algeria'),(65,'Saalfelden am Steinernen Meer','Svalbard and Jan Mayen Islands'),(66,'Cairns','Cook Islands'),(67,'Neusiedl am See','Iceland'),(68,'Brixton','Netherlands'),(69,'Newcastle-upon-Tyne','Bangladesh'),(70,'Ponsacco','Mauritania');
INSERT INTO `destination` (`id`,`city`,`country`) VALUES (71,'Flin Flon','Peru'),(72,'West Ham','Western Sahara'),(73,'San Antonio','Central African Republic'),(74,'Plainevaux','Micronesia'),(75,'Lobbes','Botswana'),(76,'Waasmunster','Faroe Islands'),(77,'Londrina','Guinea-Bissau'),(78,'Maidenhead','Western Sahara'),(79,'Port Coquitlam','Virgin Islands, United States'),(80,'Subiaco','Portugal');
INSERT INTO `destination` (`id`,`city`,`country`) VALUES (81,'Vernole','South Africa'),(82,'Erembodegem','Lesotho'),(83,'Spermalie','Eritrea'),(84,'San Pablo','Solomon Islands'),(85,'Taber','New Caledonia'),(86,'Tain','Sweden'),(87,'Dibrugarh','Côte D''Ivoire (Ivory Coast)'),(88,'Oviedo','Singapore'),(89,'Bendigo','Ethiopia'),(90,'Rimouski','Guatemala');
INSERT INTO `destination` (`id`,`city`,`country`) VALUES (91,'Fortune','Canada'),(92,'Spormaggiore','Afghanistan'),(93,'San Marcello','Nepal'),(94,'Vancouver','Burkina Faso'),(95,'Frutillar','Ethiopia'),(96,'De Klinge','Benin'),(97,'Ch‰telet','Somalia'),(98,'Bala','Qatar'),(99,'Kapolei','Algeria'),(100,'Foligno','Guinea');
